FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    php-fpm \
    php-common \
    php-mysql \
    php-curl \
    php-gd \
    php-bcmath \
    php-json \
    php-opcache \
    php-imagick \
    php-mbstring \
    php-xml \
    php-zip \
    wget \
    tar \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

RUN wget -q https://wordpress.org/latest.tar.gz -O /tmp/latest.tar.gz && \
    mkdir -p /var/tmp && \
    tar -xzf /tmp/latest.tar.gz -C /var/tmp --strip-components=1 && \
    rm /tmp/latest.tar.gz

RUN wget -q https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/Si-Achraf

RUN sed -i 's/listen = .*/listen = 0.0.0.0:9000/' /etc/php/*/fpm/pool.d/www.conf

COPY bash.sh /usr/local/bin/bash.sh
RUN chmod +x /usr/local/bin/bash.sh

CMD ["/usr/local/bin/bash.sh"]