FROM debian:12

RUN apt update && apt install -y \
    php8.2-fpm \
    php8.2-mysql \
    mariadb-client \
    wget \
    && rm -rf /var/lib/apt/lists/*


RUN sed -i 's|^listen = .*|listen = 0.0.0.0:9000|' /etc/php/8.2/fpm/pool.d/www.conf && \
    mkdir -p /run/php

WORKDIR /var/www/html

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wordpress

COPY bash.sh /usr/local/bin/bash.sh
RUN chmod +x /usr/local/bin/bash.sh

EXPOSE 9000

ENTRYPOINT ["/usr/local/bin/bash.sh"]

